<?php
/**
 * PackagePriceInfoVasTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Объявления
 *
 * API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).**
 *
 * OpenAPI spec version: 1
 * Contact: supportautoload@avito.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.32
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PackagePriceInfoVasTest Class Doc Comment
 *
 * @category    Class
 * @description Информация о пакетах дополнительных услуг для переданного списка объявлений
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PackagePriceInfoVasTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PackagePriceInfoVas"
     */
    public function testPackagePriceInfoVas()
    {
    }

    /**
     * Test attribute "quick_sale"
     */
    public function testPropertyQuickSale()
    {
    }

    /**
     * Test attribute "turbo_sale"
     */
    public function testPropertyTurboSale()
    {
    }

    /**
     * Test attribute "x10_1"
     */
    public function testPropertyX101()
    {
    }

    /**
     * Test attribute "x10_7"
     */
    public function testPropertyX107()
    {
    }

    /**
     * Test attribute "x2_1"
     */
    public function testPropertyX21()
    {
    }

    /**
     * Test attribute "x2_7"
     */
    public function testPropertyX27()
    {
    }

    /**
     * Test attribute "x5_1"
     */
    public function testPropertyX51()
    {
    }

    /**
     * Test attribute "x5_7"
     */
    public function testPropertyX57()
    {
    }
}
