<?php
/**
 * ItemApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Объявления
 *
 * API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).**
 *
 * OpenAPI spec version: 1
 * Contact: supportautoload@avito.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.32
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ItemApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ItemApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getItemInfo
     *
     * Получение информации по объявлению.
     *
     */
    public function testGetItemInfo()
    {
    }

    /**
     * Test case for getItemsInfo
     *
     * Получение информации по объявлениям.
     *
     */
    public function testGetItemsInfo()
    {
    }

    /**
     * Test case for getVasPackagePrice
     *
     * Получение информации о стоимости пакетов дополнительных услуг.
     *
     */
    public function testGetVasPackagePrice()
    {
    }

    /**
     * Test case for getVasPrices
     *
     * Получение информации о стоимости дополнительных услуг.
     *
     */
    public function testGetVasPrices()
    {
    }

    /**
     * Test case for itemStatsShallow
     *
     * Получение статистики по списку объявлений.
     *
     */
    public function testItemStatsShallow()
    {
    }

    /**
     * Test case for postCallsStats
     *
     * Получение статистики по звонкам.
     *
     */
    public function testPostCallsStats()
    {
    }

    /**
     * Test case for putItemVas
     *
     * Применение дополнительных услуг.
     *
     */
    public function testPutItemVas()
    {
    }

    /**
     * Test case for putItemVasPackageV2
     *
     * Применение пакета дополнительных услуг.
     *
     */
    public function testPutItemVasPackageV2()
    {
    }
}
